package test;

import com.asledgehammer.typescript.TypeScriptCompiler;
import com.asledgehammer.typescript.settings.Recursion;
import com.asledgehammer.typescript.settings.TypeScriptSettings;
import fmod.fmod.EmitterType;
import fmod.fmod.FMODAudio;
import fmod.fmod.FMODSoundBank;
import fmod.fmod.FMODSoundEmitter;
import org.joml.Vector2f;
import org.joml.Vector3f;
import org.lwjglx.input.Keyboard;
import se.krka.kahlua.vm.KahluaUtil;
import zombie.*;
import zombie.Lua.LuaEventManager;
import zombie.Lua.LuaManager;
import zombie.Lua.MapObjects;
import zombie.ai.GameCharacterAIBrain;
import zombie.ai.MapKnowledge;
import zombie.ai.sadisticAIDirector.SleepingEvent;
import zombie.ai.states.*;
import zombie.audio.*;
import zombie.characterTextures.BloodBodyPartType;
import zombie.characterTextures.BloodClothingType;
import zombie.characters.*;
import zombie.characters.AttachedItems.*;
import zombie.characters.BodyDamage.*;
import zombie.characters.CharacterTimedActions.LuaTimedAction;
import zombie.characters.CharacterTimedActions.LuaTimedActionNew;
import zombie.characters.Moodles.Moodle;
import zombie.characters.Moodles.MoodleType;
import zombie.characters.Moodles.Moodles;
import zombie.characters.WornItems.*;
import zombie.characters.professions.ProfessionFactory;
import zombie.characters.skills.PerkFactory;
import zombie.characters.traits.ObservationFactory;
import zombie.characters.traits.TraitCollection;
import zombie.characters.traits.TraitFactory;
import zombie.chat.ChatBase;
import zombie.chat.ChatMessage;
import zombie.chat.ChatTab;
import zombie.chat.ServerChatMessage;
import zombie.config.*;
import zombie.core.*;
import zombie.core.fonts.AngelCodeFont;
import zombie.core.logger.ZLogger;
import zombie.core.math.PZMath;
import zombie.core.properties.PropertyContainer;
import zombie.core.skinnedmodel.advancedanimation.debug.AnimatorDebugMonitor;
import zombie.core.skinnedmodel.population.*;
import zombie.core.skinnedmodel.visual.HumanVisual;
import zombie.core.skinnedmodel.visual.ItemVisual;
import zombie.core.skinnedmodel.visual.ItemVisuals;
import zombie.core.stash.Stash;
import zombie.core.stash.StashBuilding;
import zombie.core.stash.StashSystem;
import zombie.core.textures.ColorInfo;
import zombie.core.textures.Texture;
import zombie.core.znet.SteamFriend;
import zombie.core.znet.SteamUGCDetails;
import zombie.core.znet.SteamWorkshopItem;
import zombie.debug.BooleanDebugOption;
import zombie.debug.DebugLog;
import zombie.debug.DebugOptions;
import zombie.debug.DebugType;
import zombie.erosion.ErosionConfig;
import zombie.erosion.ErosionMain;
import zombie.erosion.season.ErosionSeason;
import zombie.gameStates.*;
import zombie.globalObjects.*;
import zombie.input.GameKeyboard;
import zombie.input.Mouse;
import zombie.inventory.*;
import zombie.inventory.types.*;
import zombie.iso.*;
import zombie.iso.SpriteDetails.IsoFlagType;
import zombie.iso.SpriteDetails.IsoObjectType;
import zombie.iso.areas.IsoBuilding;
import zombie.iso.areas.IsoRoom;
import zombie.iso.areas.NonPvpZone;
import zombie.iso.areas.SafeHouse;
import zombie.iso.areas.isoregion.IsoRegionLogType;
import zombie.iso.areas.isoregion.IsoRegions;
import zombie.iso.areas.isoregion.IsoRegionsLogger;
import zombie.iso.areas.isoregion.IsoRegionsRenderer;
import zombie.iso.areas.isoregion.data.DataCell;
import zombie.iso.areas.isoregion.data.DataChunk;
import zombie.iso.areas.isoregion.regions.IsoChunkRegion;
import zombie.iso.areas.isoregion.regions.IsoWorldRegion;
import zombie.iso.objects.*;
import zombie.iso.objects.interfaces.BarricadeAble;
import zombie.iso.sprite.IsoSprite;
import zombie.iso.sprite.IsoSpriteGrid;
import zombie.iso.sprite.IsoSpriteInstance;
import zombie.iso.sprite.IsoSpriteManager;
import zombie.iso.weather.*;
import zombie.iso.weather.fog.ImprovedFog;
import zombie.iso.weather.fx.IsoWeatherFX;
import zombie.modding.ActiveMods;
import zombie.network.*;
import zombie.network.packets.hit.Vehicle;
import zombie.popman.ZombiePopulationManager;
import zombie.popman.ZombiePopulationRenderer;
import zombie.radio.ChannelCategory;
import zombie.radio.RadioAPI;
import zombie.radio.RadioData;
import zombie.radio.StorySounds.*;
import zombie.radio.ZomboidRadio;
import zombie.radio.devices.DeviceData;
import zombie.radio.devices.DevicePresets;
import zombie.radio.devices.PresetEntry;
import zombie.radio.media.MediaData;
import zombie.radio.media.RecordedMedia;
import zombie.radio.scripting.*;
import zombie.randomizedWorld.RandomizedWorldBase;
import zombie.randomizedWorld.randomizedBuilding.*;
import zombie.randomizedWorld.randomizedDeadSurvivor.*;
import zombie.randomizedWorld.randomizedVehicleStory.*;
import zombie.randomizedWorld.randomizedZoneStory.*;
import zombie.scripting.ScriptManager;
import zombie.scripting.objects.*;
import zombie.ui.*;
import zombie.util.PZCalendar;
import zombie.util.list.PZArrayList;
import zombie.vehicles.*;
import zombie.world.moddata.ModData;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class ZomboidGenerator {

  public static void main(String[] args) throws IOException {

    TypeScriptSettings settings = new TypeScriptSettings();
    settings.recursion = Recursion.NONE;
    settings.readOnly = true;

    TypeScriptCompiler compiler = new TypeScriptCompiler(settings);
    compiler.add(IsoPlayer.class);
    compiler.add(Vehicle.class);
    compiler.add(BaseVehicle.class);

    compiler.add(BufferedReader.class);
    compiler.add(BufferedWriter.class);
    compiler.add(DataInputStream.class);
    compiler.add(DataOutputStream.class);
    compiler.add(Double.class);
    compiler.add(Long.class);
    compiler.add(Float.class);
    compiler.add(Integer.class);
    compiler.add(Math.class);
    compiler.add(Void.class);
    compiler.add(SimpleDateFormat.class);
    compiler.add(ArrayList.class);
    compiler.add(EnumMap.class);
    compiler.add(HashMap.class);
    compiler.add(LinkedList.class);
    compiler.add(Stack.class);
    compiler.add(Vector.class);
    compiler.add(Iterator.class);
    compiler.add(EmitterType.class);
    compiler.add(FMODAudio.class);
    compiler.add(FMODSoundBank.class);
    compiler.add(FMODSoundEmitter.class);
    compiler.add(Vector2f.class);
    compiler.add(Vector3f.class);
    compiler.add(KahluaUtil.class);
    compiler.add(DummySoundBank.class);
    compiler.add(DummySoundEmitter.class);
    compiler.add(BaseSoundEmitter.class);
    compiler.add(GameSound.class);
    compiler.add(GameSoundClip.class);
    compiler.add(AttackState.class);
    compiler.add(BurntToDeath.class);
    compiler.add(ClimbDownSheetRopeState.class);
    compiler.add(ClimbOverFenceState.class);
    compiler.add(ClimbOverWallState.class);
    compiler.add(ClimbSheetRopeState.class);
    compiler.add(ClimbThroughWindowState.class);
    compiler.add(CloseWindowState.class);
    compiler.add(CrawlingZombieTurnState.class);
    compiler.add(FakeDeadAttackState.class);
    compiler.add(FakeDeadZombieState.class);
    compiler.add(FishingState.class);
    compiler.add(FitnessState.class);
    compiler.add(IdleState.class);
    compiler.add(LungeState.class);
    compiler.add(OpenWindowState.class);
    compiler.add(PathFindState.class);
    compiler.add(PlayerActionsState.class);
    compiler.add(PlayerAimState.class);
    compiler.add(PlayerEmoteState.class);
    compiler.add(PlayerExtState.class);
    compiler.add(PlayerFallDownState.class);
    compiler.add(PlayerFallingState.class);
    compiler.add(PlayerGetUpState.class);
    compiler.add(PlayerHitReactionPVPState.class);
    compiler.add(PlayerHitReactionState.class);
    compiler.add(PlayerKnockedDown.class);
    compiler.add(PlayerOnGroundState.class);
    compiler.add(PlayerSitOnGroundState.class);
    compiler.add(PlayerStrafeState.class);
    compiler.add(SmashWindowState.class);
    compiler.add(StaggerBackState.class);
    compiler.add(SwipeStatePlayer.class);
    compiler.add(ThumpState.class);
    compiler.add(WalkTowardState.class);
    compiler.add(ZombieFallDownState.class);
    compiler.add(ZombieGetDownState.class);
    compiler.add(ZombieGetUpState.class);
    compiler.add(ZombieIdleState.class);
    compiler.add(ZombieOnGroundState.class);
    compiler.add(ZombieReanimateState.class);
    compiler.add(ZombieSittingState.class);
    compiler.add(GameCharacterAIBrain.class);
    compiler.add(MapKnowledge.class);
    compiler.add(BodyPartType.class);
    compiler.add(BodyPart.class);
    compiler.add(BodyDamage.class);
    compiler.add(Thermoregulator.class);
    compiler.add(Thermoregulator.ThermalNode.class);
    compiler.add(Metabolics.class);
    compiler.add(Fitness.class);
    compiler.add(GameKeyboard.class);
    compiler.add(LuaTimedAction.class);
    compiler.add(LuaTimedActionNew.class);
    compiler.add(Moodle.class);
    compiler.add(Moodles.class);
    compiler.add(MoodleType.class);
    compiler.add(ProfessionFactory.class);
    compiler.add(ProfessionFactory.Profession.class);
    compiler.add(PerkFactory.class);
    compiler.add(PerkFactory.Perk.class);
    compiler.add(PerkFactory.Perks.class);
    compiler.add(ObservationFactory.class);
    compiler.add(ObservationFactory.Observation.class);
    compiler.add(TraitFactory.class);
    compiler.add(TraitFactory.Trait.class);
    compiler.add(IsoDummyCameraCharacter.class);
    compiler.add(Stats.class);
    compiler.add(SurvivorDesc.class);
    compiler.add(SurvivorFactory.class);
    compiler.add(SurvivorFactory.SurvivorType.class);
    compiler.add(IsoGameCharacter.class);
    compiler.add(IsoGameCharacter.PerkInfo.class);
    compiler.add(IsoGameCharacter.XP.class);
    compiler.add(IsoGameCharacter.CharacterTraits.class);
    compiler.add(TraitCollection.TraitSlot.class);
    compiler.add(TraitCollection.class);
    compiler.add(IsoPlayer.class);
    compiler.add(IsoSurvivor.class);
    compiler.add(IsoZombie.class);
    compiler.add(CharacterActionAnims.class);
    compiler.add(HaloTextHelper.class);
    compiler.add(HaloTextHelper.ColorRGB.class);
    compiler.add(NetworkAIParams.class);
    compiler.add(BloodBodyPartType.class);
    compiler.add(Clipboard.class);
    compiler.add(AngelCodeFont.class);
    compiler.add(ZLogger.class);
    compiler.add(PropertyContainer.class);
    compiler.add(ClothingItem.class);
    compiler.add(AnimatorDebugMonitor.class);
    compiler.add(ColorInfo.class);
    compiler.add(Texture.class);
    compiler.add(SteamFriend.class);
    compiler.add(SteamUGCDetails.class);
    compiler.add(SteamWorkshopItem.class);
    compiler.add(Color.class);
    compiler.add(Colors.class);
    compiler.add(Core.class);
    compiler.add(GameVersion.class);
    compiler.add(ImmutableColor.class);
    compiler.add(Language.class);
    compiler.add(PerformanceSettings.class);
    compiler.add(SpriteRenderer.class);
    compiler.add(Translator.class);
    compiler.add(PZMath.class);
    compiler.add(DebugLog.class);
    compiler.add(DebugOptions.class);
    compiler.add(BooleanDebugOption.class);
    compiler.add(DebugType.class);
    compiler.add(ErosionConfig.class);
    compiler.add(ErosionConfig.Debug.class);
    compiler.add(ErosionConfig.Season.class);
    compiler.add(ErosionConfig.Seeds.class);
    compiler.add(ErosionConfig.Time.class);
    compiler.add(ErosionMain.class);
    compiler.add(ErosionSeason.class);
    compiler.add(AnimationViewerState.class);
    compiler.add(AnimationViewerState.BooleanDebugOption.class);
    compiler.add(AttachmentEditorState.class);
    compiler.add(ChooseGameInfo.Mod.class);
    compiler.add(DebugChunkState.class);
    compiler.add(zombie.gameStates.DebugChunkState.BooleanDebugOption.class);
    compiler.add(DebugGlobalObjectState.class);
    compiler.add(GameLoadingState.class);
    compiler.add(LoadingQueueState.class);
    compiler.add(MainScreenState.class);
    compiler.add(CGlobalObject.class);
    compiler.add(CGlobalObjects.class);
    compiler.add(CGlobalObjectSystem.class);
    compiler.add(SGlobalObject.class);
    compiler.add(SGlobalObjects.class);
    compiler.add(SGlobalObjectSystem.class);
    compiler.add(Mouse.class);
    compiler.add(AlarmClock.class);
    compiler.add(AlarmClockClothing.class);
    compiler.add(Clothing.class);
    compiler.add(Clothing.ClothingPatch.class);
    compiler.add(Clothing.ClothingPatchFabricType.class);
    compiler.add(ComboItem.class);
    compiler.add(Drainable.class);
    compiler.add(DrainableComboItem.class);
    compiler.add(Food.class);
    compiler.add(HandWeapon.class);
    compiler.add(InventoryContainer.class);
    compiler.add(Key.class);
    compiler.add(KeyRing.class);
    compiler.add(Literature.class);
    compiler.add(MapItem.class);
    compiler.add(Moveable.class);
    compiler.add(Radio.class);
    compiler.add(WeaponPart.class);
    compiler.add(ItemContainer.class);
    compiler.add(ItemPickerJava.class);
    compiler.add(InventoryItem.class);
    compiler.add(InventoryItemFactory.class);
    compiler.add(FixingManager.class);
    compiler.add(RecipeManager.class);
    compiler.add(IsoRegions.class);
    compiler.add(IsoRegionsLogger.class);
    compiler.add(IsoRegionsLogger.IsoRegionLog.class);
    compiler.add(IsoRegionLogType.class);
    compiler.add(DataCell.class);
    compiler.add(DataChunk.class);
    compiler.add(IsoChunkRegion.class);
    compiler.add(IsoWorldRegion.class);
    compiler.add(IsoRegionsRenderer.class);
    compiler.add(zombie.iso.areas.isoregion.IsoRegionsRenderer.BooleanDebugOption.class);
    compiler.add(IsoBuilding.class);
    compiler.add(IsoRoom.class);
    compiler.add(SafeHouse.class);
    compiler.add(BarricadeAble.class);
    compiler.add(IsoBarbecue.class);
    compiler.add(IsoBarricade.class);
    compiler.add(IsoBrokenGlass.class);
    compiler.add(IsoClothingDryer.class);
    compiler.add(IsoClothingWasher.class);
    compiler.add(IsoCombinationWasherDryer.class);
    compiler.add(IsoStackedWasherDryer.class);
    compiler.add(IsoCurtain.class);
    compiler.add(IsoCarBatteryCharger.class);
    compiler.add(IsoDeadBody.class);
    compiler.add(IsoDoor.class);
    compiler.add(IsoFire.class);
    compiler.add(IsoFireManager.class);
    compiler.add(IsoFireplace.class);
    compiler.add(IsoGenerator.class);
    compiler.add(IsoJukebox.class);
    compiler.add(IsoLightSwitch.class);
    compiler.add(IsoMannequin.class);
    compiler.add(IsoMolotovCocktail.class);
    compiler.add(IsoWaveSignal.class);
    compiler.add(IsoRadio.class);
    compiler.add(IsoTelevision.class);
    compiler.add(IsoStackedWasherDryer.class);
    compiler.add(IsoStove.class);
    compiler.add(IsoThumpable.class);
    compiler.add(IsoTrap.class);
    compiler.add(IsoTree.class);
    compiler.add(IsoWheelieBin.class);
    compiler.add(IsoWindow.class);
    compiler.add(IsoWindowFrame.class);
    compiler.add(IsoWorldInventoryObject.class);
    compiler.add(IsoZombieGiblets.class);
    compiler.add(RainManager.class);
    compiler.add(ObjectRenderEffects.class);
    compiler.add(HumanVisual.class);
    compiler.add(ItemVisual.class);
    compiler.add(ItemVisuals.class);
    compiler.add(IsoSprite.class);
    compiler.add(IsoSpriteInstance.class);
    compiler.add(IsoSpriteManager.class);
    compiler.add(IsoSpriteGrid.class);
    compiler.add(IsoFlagType.class);
    compiler.add(IsoObjectType.class);
    compiler.add(ClimateManager.class);
    compiler.add(ClimateManager.DayInfo.class);
    compiler.add(ClimateManager.ClimateFloat.class);
    compiler.add(ClimateManager.ClimateColor.class);
    compiler.add(ClimateManager.ClimateBool.class);
    compiler.add(WeatherPeriod.class);
    compiler.add(WeatherPeriod.WeatherStage.class);
    compiler.add(WeatherPeriod.StrLerpVal.class);
    compiler.add(ClimateManager.AirFront.class);
    compiler.add(ThunderStorm.class);
    compiler.add(ThunderStorm.ThunderCloud.class);
    compiler.add(IsoWeatherFX.class);
    compiler.add(Temperature.class);
    compiler.add(ClimateColorInfo.class);
    compiler.add(ClimateValues.class);
    compiler.add(ClimateForecaster.class);
    compiler.add(ClimateForecaster.DayForecast.class);
    compiler.add(ClimateForecaster.ForecastValue.class);
    compiler.add(ClimateHistory.class);
    compiler.add(WorldFlares.class);
    compiler.add(WorldFlares.Flare.class);
    compiler.add(ImprovedFog.class);
    compiler.add(ClimateMoon.class);
    compiler.add(IsoPuddles.class);
    compiler.add(IsoPuddles.PuddlesFloat.class);
    compiler.add(BentFences.class);
    compiler.add(BrokenFences.class);
    compiler.add(ContainerOverlays.class);
    compiler.add(IsoChunk.class);
    compiler.add(BuildingDef.class);
    compiler.add(IsoCamera.class);
    compiler.add(IsoCell.class);
    compiler.add(IsoChunkMap.class);
    compiler.add(IsoDirections.class);
    compiler.add(IsoDirectionSet.class);
//    compiler.add(IsoGridSquare.class);
    compiler.add(IsoHeatSource.class);
    compiler.add(IsoLightSource.class);
    compiler.add(IsoLot.class);
    compiler.add(IsoLuaMover.class);
    compiler.add(IsoMetaChunk.class);
    compiler.add(IsoMetaCell.class);
    compiler.add(IsoMetaGrid.class);
    compiler.add(IsoMetaGrid.Trigger.class);
    compiler.add(IsoMetaGrid.VehicleZone.class);
    compiler.add(IsoMetaGrid.Zone.class);
    compiler.add(IsoMovingObject.class);
    compiler.add(IsoObject.class);
    compiler.add(IsoObjectPicker.class);
    compiler.add(IsoPushableObject.class);
    compiler.add(IsoUtils.class);
    compiler.add(IsoWorld.class);
    compiler.add(LosUtil.class);
    compiler.add(MetaObject.class);
    compiler.add(RoomDef.class);
    compiler.add(SliceY.class);
    compiler.add(TileOverlays.class);
    compiler.add(Vector2.class);
    compiler.add(Vector3.class);
    compiler.add(WorldMarkers.class);
    compiler.add(WorldMarkers.DirectionArrow.class);
    compiler.add(WorldMarkers.GridSquareMarker.class);
    compiler.add(WorldMarkers.PlayerHomingPoint.class);
    compiler.add(SearchMode.class);
    compiler.add(SearchMode.PlayerSearchMode.class);
    compiler.add(SearchMode.SearchModeFloat.class);
    compiler.add(IsoMarkers.class);
    compiler.add(IsoMarkers.IsoMarker.class);
    compiler.add(IsoMarkers.CircleIsoMarker.class);
    compiler.add(LuaEventManager.class);
    compiler.add(MapObjects.class);
    compiler.add(ActiveMods.class);
    compiler.add(Server.class);
    compiler.add(ServerOptions.class);
    compiler.add(ServerOptions.BooleanServerOption.class);
    compiler.add(ServerOptions.DoubleServerOption.class);
    compiler.add(ServerOptions.IntegerServerOption.class);
    compiler.add(ServerOptions.StringServerOption.class);
    compiler.add(ServerOptions.TextServerOption.class);
    compiler.add(ServerSettings.class);
    compiler.add(ServerSettingsManager.class);
    compiler.add(ZombiePopulationManager.class);
    compiler.add(ZombiePopulationRenderer.BooleanDebugOption.class);
    compiler.add(RadioAPI.class);
    compiler.add(DeviceData.class);
    compiler.add(DevicePresets.class);
    compiler.add(PresetEntry.class);
    compiler.add(ZomboidRadio.class);
    compiler.add(RadioData.class);
    compiler.add(RadioScriptManager.class);
    compiler.add(DynamicRadioChannel.class);
    compiler.add(RadioChannel.class);
    compiler.add(RadioBroadCast.class);
    compiler.add(RadioLine.class);
    compiler.add(RadioScript.class);
    compiler.add(RadioScript.ExitOption.class);
    compiler.add(ChannelCategory.class);
    compiler.add(SLSoundManager.class);
    compiler.add(StorySound.class);
    compiler.add(StorySoundEvent.class);
    compiler.add(EventSound.class);
    compiler.add(DataPoint.class);
    compiler.add(RecordedMedia.class);
    compiler.add(MediaData.class);
    compiler.add(EvolvedRecipe.class);
    compiler.add(Fixing.class);
    compiler.add(Fixing.Fixer.class);
    compiler.add(Fixing.FixerSkill.class);
    compiler.add(GameSoundScript.class);
    compiler.add(Item.class);
    compiler.add(zombie.scripting.objects.Item.Type.class);
    compiler.add(ItemRecipe.class);
    compiler.add(ModelAttachment.class);
    compiler.add(ModelScript.class);
    compiler.add(MovableRecipe.class);
    compiler.add(Recipe.class);
    compiler.add(Recipe.RequiredSkill.class);
    compiler.add(Recipe.Result.class);
    compiler.add(Recipe.Source.class);
    compiler.add(ScriptModule.class);
    compiler.add(VehicleScript.class);
    compiler.add(VehicleScript.Area.class);
    compiler.add(VehicleScript.Model.class);
    compiler.add(VehicleScript.Part.class);
    compiler.add(VehicleScript.Passenger.class);
    compiler.add(VehicleScript.PhysicsShape.class);
    compiler.add(VehicleScript.Position.class);
    compiler.add(VehicleScript.Wheel.class);
    compiler.add(ScriptManager.class);
    compiler.add(ActionProgressBar.class);
    compiler.add(Clock.class);
    compiler.add(UIDebugConsole.class);
    compiler.add(ModalDialog.class);
    compiler.add(MoodlesUI.class);
    compiler.add(NewHealthPanel.class);
    compiler.add(ObjectTooltip.class);
    compiler.add(ObjectTooltip.Layout.class);
    compiler.add(ObjectTooltip.LayoutItem.class);
    compiler.add(RadarPanel.class);
    compiler.add(RadialMenu.class);
    compiler.add(RadialProgressBar.class);
    compiler.add(SpeedControls.class);
    compiler.add(TextManager.class);
    compiler.add(UI3DModel.class);
    compiler.add(UIElement.class);
    compiler.add(UIFont.class);
    compiler.add(UITransition.class);
    compiler.add(UIManager.class);
    compiler.add(UIServerToolbox.class);
    compiler.add(UITextBox2.class);
    compiler.add(VehicleGauge.class);
    compiler.add(TextDrawObject.class);
    compiler.add(PZArrayList.class);
    compiler.add(PZCalendar.class);
    compiler.add(BaseVehicle.class);
    compiler.add(EditVehicleState.class);
    compiler.add(PathFindBehavior2.BehaviorResult.class);
    compiler.add(PathFindBehavior2.class);
    compiler.add(PathFindState2.class);
    compiler.add(UI3DScene.class);
    compiler.add(VehicleDoor.class);
    compiler.add(VehicleLight.class);
    compiler.add(VehiclePart.class);
    compiler.add(VehicleType.class);
    compiler.add(VehicleWindow.class);
    compiler.add(AttachedItem.class);
    compiler.add(AttachedItems.class);
    compiler.add(AttachedLocation.class);
    compiler.add(AttachedLocationGroup.class);
    compiler.add(AttachedLocations.class);
    compiler.add(WornItems.class);
    compiler.add(WornItem.class);
    compiler.add(BodyLocation.class);
    compiler.add(BodyLocationGroup.class);
    compiler.add(BodyLocations.class);
    compiler.add(DummySoundManager.class);
    compiler.add(GameSounds.class);
    compiler.add(GameTime.class);
    compiler.add(GameWindow.class);
    compiler.add(SandboxOptions.class);
    compiler.add(SandboxOptions.BooleanSandboxOption.class);
    compiler.add(SandboxOptions.DoubleSandboxOption.class);
    compiler.add(SandboxOptions.StringSandboxOption.class);
    compiler.add(SandboxOptions.EnumSandboxOption.class);
    compiler.add(SandboxOptions.IntegerSandboxOption.class);
    compiler.add(SoundManager.class);
    compiler.add(SystemDisabler.class);
    compiler.add(VirtualZombieManager.class);
    compiler.add(WorldSoundManager.class);
    compiler.add(WorldSoundManager.WorldSound.class);
    compiler.add(DummyCharacterSoundEmitter.class);
    compiler.add(CharacterSoundEmitter.class);
    compiler.add(SoundManager.AmbientSoundEffect.class);
    compiler.add(BaseAmbientStreamManager.class);
    compiler.add(AmbientStreamManager.class);
    compiler.add(Nutrition.class);
    compiler.add(BSFurnace.class);
    compiler.add(MultiStageBuilding.class);
    compiler.add(MultiStageBuilding.Stage.class);
    compiler.add(SleepingEvent.class);
    compiler.add(IsoCompost.class);
    compiler.add(Userlog.class);
    compiler.add(Userlog.UserlogType.class);
    compiler.add(ConfigOption.class);
    compiler.add(BooleanConfigOption.class);
    compiler.add(DoubleConfigOption.class);
    compiler.add(EnumConfigOption.class);
    compiler.add(IntegerConfigOption.class);
    compiler.add(StringConfigOption.class);
    compiler.add(Faction.class);
    compiler.add(LuaManager.GlobalObject.LuaFileWriter.class);
    compiler.add(Keyboard.class);
    compiler.add(DBResult.class);
    compiler.add(NonPvpZone.class);
    compiler.add(DBTicket.class);
    compiler.add(StashSystem.class);
    compiler.add(StashBuilding.class);
    compiler.add(Stash.class);
    compiler.add(ItemType.class);
    compiler.add(RandomizedWorldBase.class);
    compiler.add(RandomizedBuildingBase.class);
    compiler.add(RBBurntFireman.class);
    compiler.add(RBBasic.class);
    compiler.add(RBBurnt.class);
    compiler.add(RBOther.class);
    compiler.add(RBStripclub.class);
    compiler.add(RBSchool.class);
    compiler.add(RBSpiffo.class);
    compiler.add(RBPizzaWhirled.class);
    compiler.add(RBOffice.class);
    compiler.add(RBHairSalon.class);
    compiler.add(RBClinic.class);
    compiler.add(RBPileOCrepe.class);
    compiler.add(RBCafe.class);
    compiler.add(RBBar.class);
    compiler.add(RBLooted.class);
    compiler.add(RBSafehouse.class);
    compiler.add(RBBurntCorpse.class);
    compiler.add(RBShopLooted.class);
    compiler.add(RBKateAndBaldspot.class);
    compiler.add(RandomizedDeadSurvivorBase.class);
    compiler.add(RDSZombiesEating.class);
    compiler.add(RDSBleach.class);
    compiler.add(RDSDeadDrunk.class);
    compiler.add(RDSGunmanInBathroom.class);
    compiler.add(RDSGunslinger.class);
    compiler.add(RDSZombieLockedBathroom.class);
    compiler.add(RDSBandPractice.class);
    compiler.add(RDSBathroomZed.class);
    compiler.add(RDSBedroomZed.class);
    compiler.add(RDSFootballNight.class);
    compiler.add(RDSHenDo.class);
    compiler.add(RDSStagDo.class);
    compiler.add(RDSStudentNight.class);
    compiler.add(RDSPokerNight.class);
    compiler.add(RDSSuicidePact.class);
    compiler.add(RDSPrisonEscape.class);
    compiler.add(RDSPrisonEscapeWithPolice.class);
    compiler.add(RDSSkeletonPsycho.class);
    compiler.add(RDSCorpsePsycho.class);
    compiler.add(RDSSpecificProfession.class);
    compiler.add(RDSPoliceAtHouse.class);
    compiler.add(RDSHouseParty.class);
    compiler.add(RDSTinFoilHat.class);
    compiler.add(RDSHockeyPsycho.class);
    compiler.add(RandomizedVehicleStoryBase.class);
    compiler.add(RVSCarCrash.class);
    compiler.add(RVSBanditRoad.class);
    compiler.add(RVSAmbulanceCrash.class);
    compiler.add(RVSCrashHorde.class);
    compiler.add(RVSCarCrashCorpse.class);
    compiler.add(RVSPoliceBlockade.class);
    compiler.add(RVSPoliceBlockadeShooting.class);
    compiler.add(RVSBurntCar.class);
    compiler.add(RVSConstructionSite.class);
    compiler.add(RVSUtilityVehicle.class);
    compiler.add(RVSChangingTire.class);
    compiler.add(RVSFlippedCrash.class);
    compiler.add(RVSTrailerCrash.class);
    compiler.add(RandomizedZoneStoryBase.class);
    compiler.add(RZSForestCamp.class);
    compiler.add(RZSForestCampEaten.class);
    compiler.add(RZSBuryingCamp.class);
    compiler.add(RZSBeachParty.class);
    compiler.add(RZSFishingTrip.class);
    compiler.add(RZSBBQParty.class);
    compiler.add(RZSHunterCamp.class);
    compiler.add(RZSSexyTime.class);
    compiler.add(RZSTrapperCamp.class);
    compiler.add(RZSBaseball.class);
    compiler.add(RZSMusicFestStage.class);
    compiler.add(RZSMusicFest.class);
    compiler.add(MapGroups.class);
    compiler.add(BeardStyles.class);
    compiler.add(BeardStyle.class);
    compiler.add(HairStyles.class);
    compiler.add(HairStyle.class);
    compiler.add(BloodClothingType.class);
    compiler.add(WeaponType.class);
    compiler.add(IsoWaterGeometry.class);
    compiler.add(ModData.class);
    compiler.add(WorldMarkers.class);
    compiler.add(ChatMessage.class);
    compiler.add(ChatBase.class);
    compiler.add(ServerChatMessage.class);
    compiler.add(ChatTab.class);
    compiler.add(LuaManager.GlobalObject.class);

    compiler.walk();

    FileWriter writer = new FileWriter("default.d.ts");
    writer.write(compiler.compile());
    writer.flush();
    writer.close();
  }
}
